---
- name: Install and update packages
  hosts: all
  vars:
    apply_to_user: verzola
  tasks:
    - name: Add gpg keys
      become: true
      with_items:
        - https://apt.releases.hashicorp.com/gpg
        - https://deb.nodesource.com/gpgkey/nodesource.gpg.key
        - https://cli.github.com/packages/githubcli-archive-keyring.gpg
        - https://download.docker.com/linux/ubuntu/gpg
      apt_key:
        url: "{{ item }}"
        state: present

    - name: Add ppas repositories
      become: true
      with_items:
        - ppa:neovim-ppa/stable
        - ppa:ansible/ansible
        - deb [arch=amd64] https://apt.releases.hashicorp.com {{ ansible_lsb.codename }} main
        - deb https://deb.nodesource.com/node_16.x {{ ansible_lsb.codename }} main
        - deb [arch=amd64] https://cli.github.com/packages stable main
        - deb https://download.docker.com/linux/ubuntu focal stable
      apt_repository:
        validate_certs: no
        repo: "{{ item }}"
        state: present
        update_cache: true

    - name: Install packages
      become: true
      apt:
        update_cache: yes
        name:
          - apt-transport-https
          - bat
          - build-essential
          - ca-certificates
          - curl
          - g++
          - gcc
          - gh
          - git
          - htop
          - make
          - neofetch
          - neovim
          - nodejs
          - openjdk-11-jdk
          - openssh-server
          - php-cli
          - python3
          - python3-pip
          - software-properties-common
          - terraform
          - tmux
          - unzip
          - vagrant
          - virtualbox
          - zip
          - zsh
          - lm-sensors
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: latest

    - name: Update packages
      become: true
      apt:
        upgrade: dist

    - name: Remove useless packages from the cache
      become: true
      apt:
        autoclean: yes

    - name: Remove dependencies that are no longer required
      become: true
      apt:
        autoremove: yes

    - name: Install "yarn" node.js package globally.
      become: true
      npm:
        name: yarn
        global: yes

    - name: Configure Git username
      git_config:
        name: user.name
        scope: global
        value: 'Gustavo Verzola'

    - name: Configure Git e-mail
      git_config:
        name: user.email
        scope: global
        value: verzola@gmail.com

    - name: Create my projects folder
      file:
        path: ~/projects/verzola
        state: directory

    - name: Clone zsh configuration
      git:
        repo: https://github.com/verzola/.zshrc.git
        dest: ~/projects/verzola/zshrc
        clone: yes
        update: yes

    - name: Create zsh symbolic link
      file:
        src: ~/projects/verzola/zshrc/.zshrc
        dest: ~/.zshrc
        state: link

    - name: Clone tmux configuration
      git:
        repo: https://github.com/verzola/.tmux.conf.git
        dest: ~/projects/verzola/tmux.conf
        clone: yes
        update: yes

    - name: Install tmux plugin manager
      git:
        repo: https://github.com/tmux-plugins/tpm
        dest: ~/.tmux/plugins/tpm
        clone: yes
        update: yes

    - name: Create tmux symbolic link
      file:
        src: ~/projects/verzola/tmux.conf/.tmux.conf
        dest: ~/.tmux.conf
        state: link

    - name: Install tmux plugins
      shell: ~/.tmux/plugins/tpm/scripts/install_plugins.sh

    - name: Create neovim autoload folder
      file:
        path: ~/.local/share/nvim/site/autoload
        state: directory

    - name: Install vim-plug in neovim
      get_url:
        dest: "~/.local/share/nvim/site/autoload/plug.vim"
        url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

    - name: Clone vim configuration
      git:
        repo: https://github.com/verzola/.vimrc.git
        dest: ~/projects/verzola/vimrc
        clone: yes
        update: yes

    - name: Create neovim config folder
      file:
        path: ~/.config/nvim
        state: directory

    - name: Create neovim symbolic link
      file:
        src: ~/projects/verzola/vimrc/.vimrc
        dest: ~/.config/nvim/init.vim
        state: link

    - name: Clone aliases configuration
      git:
        repo: https://github.com/verzola/aliases.git
        dest: ~/projects/verzola/aliases
        clone: yes
        update: yes

    - name: change user shell to zsh
      become: true
      user:
        name: "{{ apply_to_user }}"
        shell: /bin/zsh

    - name: Add user to docker group
      become: true
      user:
        name: "{{ apply_to_user }}"
        group: docker
